#!/bin/bash

set -e

cd /usr/share/postgresql/9.5/tsearch_data

ls -lha

#we need to be root to do this junk...

rm -rf tmp
mkdir tmp
cd tmp

# is this a safe place to get dictionary from?
wget https://downloads.sourceforge.net/project/wordlist/speller/2017.01.22/hunspell-en_US-2017.01.22.zip -O t.zip
unzip t.zip


#affix
mv en_US.aff ../en_us.affix


# Remove first line
sed -i 1d en_US.dic

# Concat the dic and dic_delta, sort alphabetically and remove the leading blank line (leaves the ending newline intact)
cat en_US.dic | sort > ../en_us.dict
sed -i 1d ../en_us.dict


sudo -u postgres psql -c "DROP TEXT SEARCH DICTIONARY IF EXISTS ispell_en_us; CREATE TEXT SEARCH DICTIONARY ispell_en_us (template = ispell, dictfile = en_us, afffile = en_us, stopwords = english);"

sudo -u postgres psql -c "ALTER TEXT SEARCH CONFIGURATION english ALTER MAPPING FOR asciiword, asciihword, hword_asciipart, word, hword, hword_part
    WITH ispell_en_us, english_stem;"
    
    
cd ..
rm -rf tmp


ls -lha




