# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "geerlingguy/ubuntu1604"
  config.vm.network :private_network, ip: "10.42.52.94"
  config.vm.synced_folder "..", "/host"
  config.vm.provision "shell", path: "Vagrantfile.sh"

config.vm.provider "virtualbox" do |v|
  v.memory = 1024
end

end


