#!/bin/bash
### BEGIN INIT INFO
# If you wish the Daemon to be lauched at boot / stopped at shutdown :
#
#    On Debian-based distributions:
#      INSTALL : update-rc.d scriptname defaults
#      (UNINSTALL : update-rc.d -f  scriptname remove)
#
#    On RedHat-based distributions (CentOS, OpenSUSE...):
#      INSTALL : chkconfig --level 35 scriptname on
#      (UNINSTALL : chkconfig --level 35 scriptname off)
#
# chkconfig:         2345 90 60
# Provides:          dportal
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: forever running dportal
# Description:       dportal
### END INIT INFO
#
# initd a node app
# Based on a script posted by https://gist.github.com/jinze at https://gist.github.com/3748766
#


FOREVER="/usr/local/bin/forever"
NODE="/usr/bin/node"

DIR="/portald"
APP="$DIR/dportal/dportal/js/serv.js"

LOGDIR="$DIR/logs"
LOGFILE="$LOGDIR/portald"




source $DIR/box/env.sh


# switch from root to $PGUSER

if [ $UID -eq 0 ]; then
	exec su "$PGUSER" "$0" "$@"
fi



start() {
	echo "Starting $APP"

	PATH=/usr/local/bin:$PATH
	cd $DIR
	$FOREVER start -p ${LOGDIR} --pidFile ${LOGFILE}.pid -l ${LOGFILE}.log -e ${LOGFILE}.err -o ${LOGFILE}.out -a -d -c "$NODE" $APP
	RETVAL=$?
}

restart() {
	echo "Restarting $APP"
	cd $DIR
	$FOREVER restart -p ${LOGDIR} $APP
	RETVAL=$?
}

stop() {
	echo "Shutting down $APP"
	cd $DIR
	$FOREVER stop -p ${LOGDIR} $APP
	RETVAL=$?
}

status() {
	echo "Status $APP"
	cd $DIR
	$FOREVER list -p ${LOGDIR}
	RETVAL=$?
}

log() {
	echo "tail -f $LOGFILE"
	cd $DIR
	tail -f $LOGFILE
	RETVAL=$?
}

cron() {
	echo "cron $APP"
	cd $DIR
	bin/cron.sh
	RETVAL=$?
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	status)
		status
		;;
	restart)
		restart
		;;
	log)
		log
		;;
	cron)
		cron
		;;
	*)
		echo "Usage:  {start|stop|status|restart|log}"
		exit 1
		;;
esac
exit $RETVAL
