# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "generic/ubuntu2010"
  config.vm.network :private_network, ip: "192.168.56.19"
  config.vm.synced_folder "..", "/host", owner: "vagrant", group: "vagrant", type: "virtualbox"
  config.vm.synced_folder "../..", "/hostup", owner: "vagrant", group: "vagrant", type: "virtualbox"
  config.vm.provision "shell", path: "Vagrantfile-always.sh", run: 'always'
  config.vm.provision "shell", path: "Vagrantfile.sh"

config.vm.provider "virtualbox" do |v|
  v.memory = 2048
end

end


